Parameters:
  EC2InstancePublicIP:
    Type: String
    Description: Public IP address of the EC2 instance

Resources:
  leesa9019432ApiGateway:
    Type: 'AWS::ApiGateway::RestApi'
    Properties:
      Name: 'leesa9019432Api'

  leesa9019432ApiResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      ParentId:
        Fn::GetAtt:
          - 'leesa9019432ApiGateway'
          - 'RootResourceId'
      PathPart: 'api'

  leesa9019432ApiDataResource:
    Type: 'AWS::ApiGateway::Resource'
    Properties:
      ParentId:
        Ref: 'leesa9019432ApiResource'
      PathPart: 'data'
      RestApiId:
        Ref: 'leesa9019432ApiGateway'

  leesa9019432ApiMethod:
    Type: 'AWS::ApiGateway::Method'
    Properties:
      AuthorizationType: 'NONE'
      HttpMethod: 'GET'
      ResourceId:
        Ref: 'leesa9019432ApiDataResource'
      RestApiId:
        Ref: 'leesa9019432ApiGateway'
      Integration:
        IntegrationHttpMethod: 'GET'
        Type: 'HTTP_PROXY'
        Uri: !Sub 'http://${EC2InstancePublicIP}:80/api/data'

Outputs:
  ApiEndpoint:
    Value: !Sub 'https://${leesa9019432ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/api/data'
    Description: URL of the API Gateway endpoint
