name: Deploy Infrastructure

on:
  push:
    branches:
      - main
      - dev

jobs:
  setup-aws-cli:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        id: setup-aws-cli
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Export AWS Region 
        run: echo "AWS_REGION=us-east-1" >> $GITHUB_ENV

  deploy-s3:
    runs-on: ubuntu-latest
    needs: setup-aws-cli

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy S3 Bucket
        run: |
          aws cloudformation deploy \
            --template-file s3-bucket.yaml \
            --stack-name s3-bucket-stack \
            --capabilities CAPABILITY_NAMED_IAM
            --region $AWS_REGION

  deploy-iam-roles:
    runs-on: ubuntu-latest
    needs: [setup-aws-cli, deploy-s3]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy IAM Roles
        run: |
          aws cloudformation deploy \
            --template-file iam-roles.yaml \
            --stack-name iam-roles-stack \
            --capabilities CAPABILITY_NAMED_IAM

  deploy-ec2:
    runs-on: ubuntu-latest
    needs: [setup-aws-cli, deploy-iam-roles]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy EC2 Instance
        run: |
          aws cloudformation deploy \
            --template-file ec2-instance.yaml \
            --stack-name ec2-instance-stack \
            --capabilities CAPABILITY_NAMED_IAM

      - name: Get EC2 Public IP
        id: get-ec2-ip
        run: |
          EC2_PUBLIC_IP=$(aws cloudformation describe-stacks \
            --stack-name ec2-instance-stack \
            --query "Stacks[0].Outputs[?OutputKey=='EC2InstancePublicIP'].OutputValue" \
            --output text)
          echo "EC2_PUBLIC_IP=$EC2_PUBLIC_IP" >> $GITHUB_ENV

  deploy-api-gateway:
    runs-on: ubuntu-latest
    needs: [setup-aws-cli, deploy-ec2]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy API Gateway
        env:
          EC2_PUBLIC_IP: ${{ env.EC2_PUBLIC_IP }}
        run: |
          aws cloudformation deploy \
            --template-file api-gateway.yaml \
            --stack-name api-gateway-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides EC2InstancePublicIP=${{ env.EC2_PUBLIC_IP }}
