name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}

  build:
    runs-on: ubuntu-latest
    needs: source
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: List Files for Debugging
        run: ls -R  
      - name: Install Dependencies
        run: npm install
      - name: Compile Application
        run: npm run build
      - name: Validate CloudFormation Templates
        run: |
          aws cloudformation validate-template --template-body file://cloudformation/s3.yaml
          aws cloudformation validate-template --template-body file://cloudformation/iam.yaml
          aws cloudformation validate-template --template-body file://cloudformation/lambda.yaml
          aws cloudformation validate-template --template-body file://cloudformation/api-gateway.yaml

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Unit Tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'
      - name: Deploy S3 Bucket
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/s3.yaml \
            --stack-name frontend-s3-bucket
      - name: Deploy IAM Role
        run: |
          aws