name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - dev

jobs:
  source:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

  build:
    runs-on: ubuntu-latest
    needs: source
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Change to src directory
        run: cd src

      - name: Install Dependencies
        working-directory: ./src
        run: npm install

      - name: Compile Application
        working-directory: ./src
        run: npm run build

      - name: Validate CloudFormation Template
        run: aws cloudformation validate-template --template-body file://cloudformation/infrastructure.yaml

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Change to src directory
        run: cd tests

      - name: Run Unit Tests
        working-directory: ./tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      - name: Deploy Infrastructure
        run: |
          aws cloudformation deploy \
            --template-file cloudformation/infrastructure.yaml \
            --stack-name my-infrastructure-stack \
            --capabilities CAPABILITY_NAMED_IAM \
            --parameter-overrides LambdaS3Bucket=my-lambda-code-bucket

      - name: Sync S3 Bucket
        run: |
          aws s3 sync public/ s3://leesa9019432-frontend-bucket-9121857 --region us-east-1
